### ISSUE TITLE
Property Classifier_Matching_Rule allows value "Complement"

### ISSUE THREAD

**Issue by lwrage** [saeaadl/aadlv2.2#1]
The definition of property `Classifier_Matching_Rule` lists the enumeration literal `Complement`. The meaning of this value is not described in the standard. I assume it should be removed.

**Comment by reteprelief** [comment]
Remove "Complement" from the definition of the property Classifier_Matching_Rule

**Comment by reteprelief** [comment]
already removed in OSATE.
