### ISSUE TITLE
Contradicting Size_Range standard property type definition

### ISSUE THREAD

**Issue by buzden** [saeaadl/aadlv2.2#17]
It was strange to realize that both `AADL_Project` and `Modeling_Properties` property sets (which both are predeclared ones) contain `Size_Range` type declaration. This fact itself gives some uncertainty.

What wonders more is that these two definitions are different: one is a `range` of `Size` (which in its turn is an `integer` with units of information amount) and the second one is just a `range` of `integer`s. In `Modeling_Properties` property set it is used only for the property named `Acceptable_Array_Size` which definition seems to be consistent to the definition of "just a range of integers" while the rest of the standard uses `Size_Range` in the meaning of "range of integers with information amount unit".

So, I would like to consider `Size_Range` to be defined only in the `AADL_Project` property set and `Acceptable_Array_Size` to be defined as `list of range of aadlinteger`.

Probably, for v3 we should consider a better name for a value with information amount unit rather than `Size' due to its ambiguity.

**Comment by reteprelief** [comment]
The property in Modeling_Properties is called Array_Size_Range.

I agree that for memory/storage related size we may want to change the name to something more specific.
