### ISSUE TITLE
Operational systems are not required to have bound prototypes

### ISSUE THREAD

**Issue by AaronGreenhouse** [saeaadl/aadlv2.2#19]
I don't see a rule that requires operational systems to have all their prototypes bound.  Suppose we have

```
package package1
public
	system s
		-- ...
	end s;

	system implementation s.i
	prototypes
		X: bus;
		-- ...
	subcomponents
		b: bus X;
		-- ...
	end s.i;

	system T.i
	subcomponents
		sub1: system s.i -- no prototype binding
		-- ...
	end T.i
end package1;
```

There is no rule that says `T.i` is not an operational/completely instantiable even though its subcomponent `sub1` is missing a prototype binding.

This seems wrong.

**Comment by jjhugues** [comment]
Here is a corrected example, it generates a NPE

`package issue19
public
	system s
		-- ...
	end s;

	system implementation s.i
		prototypes
			X: bus;
		-- ...
		subcomponents
			b: bus X;
	-- ...
	end s.i;

	system T

	end T;

	system implementation T.i
	subcomponents
		sub1:

	system s.i; -- no prototype binding
-- ...
end T.i;
	
end issue19;`

**Comment by jjhugues** [comment]
As pointed out by Peter, this is a v3 topic, closing
