### ISSUE TITLE
"Subtype" is not a valid value of property Classifer_Matching_Rule

### ISSUE THREAD

**Issue by lwrage** [saeaadl/aadlv2.2#2]
Paragraphs (21) and (22) in section 9.2.2 Port Connection Topology refer to a `Classifier_Matching_Rule` value `Subtype`. This is not a valid enumeration literal for the property.

**Comment by reteprelief** [comment]
Delete "Subtype"

**Comment by reteprelief** [comment]
Already absent in OSATE implementation
