### ISSUE TITLE
Inconsistent description of aggregate data ports

### ISSUE THREAD

**Issue by lwrage** [saeaadl/aadlv2.2#3]
Aggregate data ports are described in 8.3.1 (15) and 9.2.2 (21).
8.3.1 (15) uses data implementation with data subcomponents, whereas 9.2.2 (21) additionally requires data access features in the data type.
The syntax for connection declarations supports a data subcomponent as connection end.

**Comment by reteprelief** [comment]
Delete "externally visible through provides data access declarations" in 9.2.2 (21)
