### ISSUE TITLE
Allow renames of property sets

### ISSUE THREAD

**Issue by stevevestal** [saeaadl/aadlv2.2#32]
Packages can be renamed but not property sets.  The declaration "renames my_properties::all" in particular may be convenient for users.  It's just a convenience, but it might be a very minor change to implement.

**Comment by reteprelief** [comment]
In V3 taken care of by import declaration.

**Comment by reteprelief** [comment]
2.2 compliant tools will not be able to process this. It is implementable though.
Not included as an errata.
