### ISSUE TITLE
"Initial" is allowed in requires modes 

### ISSUE THREAD

**Issue by lwrage** [saeaadl/aadlv2.2#33]
The last sentence in legality rule 12 (L2) is not sufficient. There should be an explicit statement that "initial" is not allowed in requires modes.

**Comment by reteprelief** [comment]
The sentence: This rule does not apply to requires modes subclauses.

The grammar rule already states that there is no "initial" keyword.

We can change the sentence to: 
Requires modes subclauses must not contain the "initial" keyword.
