### ISSUE TITLE
Flow implemenation naming rules N2 is not clear about feature groups.

### ISSUE THREAD

**Issue by reteprelief** [saeaadl/aadlv2.2#4]
Currently they state 
(N1)	The flow identifier of a flow implementation must name a flow specification in the component type.  A flow implementation name may appear more than once in each component implementation, either as alternative flows under different modes or transitions (using in modes), or to represent multiple flows for the same flow specification such as replicated flows to support redundancy or different flows for different elements of feature groups.
(N2)	The in_flow and out_flow feature identifier in a flow implementation must refer to the same in_flow and out_flow feature as the flow specification it implements. 

The last part of N1 indicates that users can have multiple flow implementations for the same flow spec, each identifying a flow for an element in a feature group. In other words, the flow spec identifies the feature group, while the flow implementation identifies the feature group and an element in the feature group as source and destination. NOTE: users could specify separate flow specs for each element in a feature group and then the flow implementation must point to the same - however this does not take advantage of the feature group abstraction and users have to define separate flow specs and end to end flows for each feature group element while the feature group connection as a single declaration implies a connection for each element.

Proposed correction to N2:
Add: In the case of an in_flow and out_flow feature group in the flow specification, the flow implementation may refer to an element within the respective feature group.

**Comment by lwrage** [comment]
There's also a legality rule!
(L3) The in_flow feature of a flow implementation must be identical to the in_flow feature of the corresponding flow specification. The out_flow feature of a flow implementation must be identical to the out_flow feature of the corresponding flow specification.

**Comment by reteprelief** [comment]
Additional text for N2 (see above)
New test for L3: "The in_flow feature or feature group reference of a flow implementation must be the same as the in_flow feature or feature group reference of the corresponding flow specification. The out_flow feature or feature group reference of a flow implementation must be the same as the out_flow feature or feature group reference of the corresponding flow specification."
