### ISSUE TITLE
Allow end to end flow specifications

### ISSUE THREAD

**Issue by stevevestal** [saeaadl/aadlv2.2#42]
The standard now allows end to end flows to be named inside other end to end flow implementation declarations, "flow_path_subcomponent_flow_or_etef_identifier" in the grammar.  The standard permits an e2e flow to start with either a specified flow path or flow source (or component); and to end with either a specified flow path or flow sink.  An e2e flow implementation can start or end in the same way a flow path, source, or sink can start or end.  

The standard currently imposes the restriction "The end-to-end flow identifier referenced in an end-to-end flow declaration must name an end-to-end flow in the name space of the same component implementation."

End to end flow implementations can begin or end the same way as source, path, or sink implementations.  Is there a reason to forbid users from making a flow implementation visible in the component type as an e2e flow specification?  Such flows would appear as end to end flows in the generated instance of a model, and their elements might also appear as a portion of other e2e flows declared by users of that type of component.

Is there any distinction between flow sources, paths, and sinks; and end to end flows; other than one requires flow type specifications and the other forbids them?

**Comment by stevevestal** [comment]
Unless someone else sees a pressing need for this (I do not), I recommend this be put in the pile of issues to consider when updating flow declarations for V3.

**Comment by jjhugues** [comment]
- [ ] Consider this for v3 as a global clean-up on flows
