### ISSUE TITLE
Clarify requirements and permissions for subprogram classifiers in call sequences

### ISSUE THREAD

**Issue by stevevestal** [saeaadl/aadlv2.2#6]
See an OSATE issue filed for a discussion and example,

https://github.com/osate/osate2-core/issues/796

**Comment by reteprelief** [comment]
Steve proposes that we remove the ability to declare subprogram calls with reference to a subprogram classifier, not a provided/required classifier or library.

**Comment by reteprelief** [comment]
Peter thinks we may just add a note that it is ambiguous or it has a default interpretation of one instance in a process. Jerome will look at the code generation annex to see how they interpret it there.

**Comment by reteprelief** [comment]
Jerome: Should we consider removing subprogram calls for V3?

**Comment by reteprelief** [comment]
Agreed to go with the editorial comment approach (two comments earlier).

**Comment by reteprelief** [comment]
Add the following text to "Processing Requirements and Permissions" section of 5.2:
"When users specify calls in a call sequence with a reference to a classifier then the subprogram instance to be called is not specified as part of the model but left as choice to the implementer. This may be a subprogram implementation in a library that may or may not be shared."
