### ISSUE TITLE
Standard refers to undefined lexical element character_literal

### ISSUE THREAD

**Issue by lwrage** [saeaadl/aadlv2.2#7]
15.2 (1), (3), and (7) refer to lexical elements, including one named _character_literal_. However, character literals don't exist in AADL.

**Comment by reteprelief** [comment]
From Ada Reference Manual (as for other parts of AADL Section 15):
A character_literal is formed by enclosing a graphic character between two apostrophe characters.
character_literal ::= 'graphic_character'
Examples of character literals: 
'A'     '*'     '''     ' '
