### ISSUE TITLE
*_swap_execution_time description inconsistency

### ISSUE THREAD

**Issue by buzden** [saeaadl/aadlv2.2#9]
`process_swap_execution_time` and `thread_swap_execution_time` properties are in _standard properties_ sections both for `processor`s and `virtual processor`s (sections 6.1 and 6.2 respectively). But definition of these properties at A.3(3) contain only `processor` in the `applies to` clause.
These two appearings must be consistent.

**Comment by reteprelief** [comment]
Add "virtual processor" to the applies to of the definition of both properties.
Also add it to the "implementation" i.e., the definition in OSATE.
